### ISSUE TITLE
Dashboard: Log a symptom

### ISSUE THREAD

**Issue by rrabinovitch** [gabichuelas/mset_app#17]
As an authenticated user,
On the dashboard page,
I see a section to log a symptom I'm experiencing.
This section includes a "symptom" dropdown field, a "date-time" field, an "additional notes" field and a "save" button.

When I select a symptom from the dropdown menu,
And enter a date and time,
And optionally enter a note,
And click the "save" button,"
I see a flash message confirming the new log,
And I now see that log in the recent logs list.

**Implementation details:**
- [x] the symptoms field is a dropdown menu populated with a uniqued list of symptoms generated based on user's medication list using the [openFDA Product Labeling API](https://open.fda.gov/apis/drug/label/understanding-the-api-results/), `https://api.fda.gov/drug/label.json?search=adverse_reactions:#{med_name}&limit=5"`
- [x] create `Logs` table: clicking "Log symptom" button creates a record that saves the `user_id`, `symptom_id`, `time`, and `note`
- [x] sad path: if "date" or "symptom" fields aren't filled out and a user clicks the "Log symptom" button, a flash message indicates there are form fields with missing info

**Comment by ejdelsztejn** [comment]
> **Consider simpler alternative: I will select the "other" option and add details about the symptom I experienced in the "additional notes" form field"

Yeah, I think that this could work, although it could also be useful to have a `User` create a new `Symptom` and then be able to quickly select it again whenever creating a `Log` (as you initially described.)

**Comment by rrabinovitch** [comment]
I'm separating the 'log an unlisted symptom' part of this user story into another issue so we can keep track of that as a different user story that still needs to be implemented
