### ISSUE TITLE
Edit medications

### ISSUE THREAD

**Issue by rrabinovitch** [gabichuelas/mset_app#20]
As an authenticated user with medications on my meds list,
When I'm on the dashboard page,
And I click the "Edit medications" button,
I am redirected to an Edit medications page,
Where I see a list displaying any current medications on my list each accompanied by a "Delete" button,
As well as a button to add a new medication to my list,
Which takes me through the process executed by story #13 

**Implementation details:**

**Comment by ejdelsztejn** [comment]
> Implementation details:

`User.medications.all`? List them and enable the user to delete them.
