### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by rrabinovitch** [gabichuelas/mset_app#21]
As an authenticated user,
On any page,*
I see a "Logout" button in the top right.
When I click the "Logout" button,
My session is ended,**
And I am redirected to the root path.

*Or just dashboard?
**Not sure if this is the right terminology

**Implementation details:**
- [x] set up `#delete` (destroy?) action in `SessionsController`

**Comment by ejdelsztejn** [comment]
I think that Logout should be on all pages in the top right corner.
