### ISSUE TITLE
Extension: Medication Show Page

### ISSUE THREAD

**Issue by gabichuelas** [gabichuelas/mset_app#55]
User can click on medication from their list,
and they can see a medication show page with medication brand_name, generic_name (if we're still using that), and a list of associated side effects (can pull from MedicationSymptoms table). 

- consider adding a delete button here too so they don't have to go back to previous page to delete it

**bonus:**
- have fields to enter prescribing doctor and dosage
- this is just for fun, we're not using it for anything other than to make this page more useful/interesting.
- we could even have a short description of the medication, however we would need to make another api call for that (that we could then save to a new column in the Medications table if we really wanted to)

**Comment by ejdelsztejn** [comment]
If we get to this, can I take the lead on it?
