### ISSUE TITLE
Welcome page

### ISSUE THREAD

**Issue by rrabinovitch** [gabichuelas/mset_app#7]
As a visitor,
When I visit the root path,
I see a welcome page with "Sign Up" / "Log In" buttons,
And a short description of the app

**Implementation details:**
- [x] set up `WelcomeController`
- [x] set up root route

**Comment by ejdelsztejn** [comment]
This looks good.  Gaby's set up yesterday any my addition of Sign Up/ Logi In buttons should have this issue complete.
I will push up those changes.
