### ISSUE TITLE
Cleanup: UI Changes

### ISSUE THREAD

**Issue by gabichuelas** [gabichuelas/mset_app#76]
- Finalize nav bar (if app name is a link, make sure it links to /root), remove other options besides Dashboard and See All Logs?
  - [x] App name links to /root
  - [x] Double check path for 'dashboard' link
  - [x] See All Logs routes to /logs
  - [x] Remove other options in nav bar

- [x] Spruce up 'log a symptom' form fields with bootstrap.. 
- [x] ~find alternate date /time picker to match in bootstrap?~

- [ ] Finish changing all buttons and links to bootstrap styling (blue primary button class)
- [ ] style medication show page
- [ ] style add medication flow
- [x] Add background image to /root, welcome page
- [x] Change background color for nav bar?

**Comment by rrabinovitch** [comment]
<img width="1063" alt="Screen Shot 2020-09-18 at 1 37 49 PM" src="https://user-images.githubusercontent.com/62635544/93638232-2c3f5900-f9b4-11ea-9310-d42b9d4eb1e8.png">
