### ISSUE TITLE
Welcome page: User registration

### ISSUE THREAD

**Issue by rrabinovitch** [gabichuelas/mset_app#8]
As a visitor,
When I visit the root path,
And I click the "Sign Up" button,
And am redirected to a page where I can register for the app using my gmail account

**Implementation details:**
- [x] create `Users` table
- [x] implement OmniAuth Google with authorization for accessing user email or profile: [Google OAuth 2.0 docs](https://developers.google.com/identity/protocols/oauth2); 
[OmniAuth Google docs](https://github.com/zquestz/omniauth-google-oauth2)
- [x] include appropriate scopes for the users authorization. See documentation [here](https://developers.google.com/calendar/auth)
- [x] tests the handshake using OmniAuth mock_auth; see docs [here](https://github.com/omniauth/omniauth/wiki/Integration-Testing)

**Comment by ejdelsztejn** [comment]
Great!

The `Users` table is complete, and Michael began to set up a test yesterday for OmniAuth Google (I'm not sure where we are at with that, maybe @michaeljevans  can give some insight.)  The scopes should be correct along with the use of `mock_auth`.
