### ISSUE TITLE
Schema Design

### ISSUE THREAD

**Issue by ejdelsztejn** [gabichuelas/mset_app#86]
This issue contains the file for our schema design for the readme.  **Please do not delete.**

<img width="928" alt="Screen Shot 2020-09-17 at 12 23 49 PM" src="https://user-images.githubusercontent.com/43380627/93499143-a4d4e580-f8e0-11ea-943d-680a95ff4322.png">

**Comment by rrabinovitch** [comment]
<img width="958" alt="Screen Shot 2020-09-17 at 11 22 35 AM" src="https://user-images.githubusercontent.com/62635544/93505433-178d9300-f8d8-11ea-8b65-afb599e98ec3.png">

application architecture
